/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface EyeLandmarks {
  'irisCenter' : Point2D,
  'lateralCanthus' : Point2D,
  'medialCanthus' : Point2D,
}
export interface Point2D { 'x' : number, 'y' : number }
export interface SessionData {
  'defectiveEye' : { 'lateralCanthus' : Point2D, 'medialCanthus' : Point2D },
  'normalEye' : EyeLandmarks,
  'calculatedIris' : Point2D,
}
export interface _SERVICE {
  'getAllSessionsSorted' : ActorMethod<[], Array<SessionData>>,
  'getSession' : ActorMethod<[], SessionData>,
  'hasSession' : ActorMethod<[], boolean>,
  'saveSession' : ActorMethod<[SessionData], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];