/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Point2D = IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 });
export const EyeLandmarks = IDL.Record({
  'irisCenter' : Point2D,
  'lateralCanthus' : Point2D,
  'medialCanthus' : Point2D,
});
export const SessionData = IDL.Record({
  'defectiveEye' : IDL.Record({
    'lateralCanthus' : Point2D,
    'medialCanthus' : Point2D,
  }),
  'normalEye' : EyeLandmarks,
  'calculatedIris' : Point2D,
});

export const idlService = IDL.Service({
  'getAllSessionsSorted' : IDL.Func([], [IDL.Vec(SessionData)], ['query']),
  'getSession' : IDL.Func([], [SessionData], []),
  'hasSession' : IDL.Func([], [IDL.Bool], ['query']),
  'saveSession' : IDL.Func([SessionData], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Point2D = IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 });
  const EyeLandmarks = IDL.Record({
    'irisCenter' : Point2D,
    'lateralCanthus' : Point2D,
    'medialCanthus' : Point2D,
  });
  const SessionData = IDL.Record({
    'defectiveEye' : IDL.Record({
      'lateralCanthus' : Point2D,
      'medialCanthus' : Point2D,
    }),
    'normalEye' : EyeLandmarks,
    'calculatedIris' : Point2D,
  });
  
  return IDL.Service({
    'getAllSessionsSorted' : IDL.Func([], [IDL.Vec(SessionData)], ['query']),
    'getSession' : IDL.Func([], [SessionData], []),
    'hasSession' : IDL.Func([], [IDL.Bool], ['query']),
    'saveSession' : IDL.Func([SessionData], [], []),
  });
};

export const init = ({ IDL }) => { return []; };